# Contents Of DB1(2)
- [자바 예외의 이해](#자바-예외의-이해)
  - [함부로 Exception으로 처리하거나 던지면 안되는 이유](#함부로-exception으로-처리하거나-던지면-안되는-이유) 
  - [자바 예외 계층](#자바-예외-계층)
  - [체크 예외와 언체크 예외](#체크-예외와-언체크-예외)
- [체크예외 활용](#체크-예외-활용)
  - [체크예외의 문제점](#체크-예외의-문제점)
- [언체크 예외 활용](#언체크-예외-활용)
- []






###### Reference
- **(main)** 인프런 김영한 스프링 DB 1편 : https://www.inflearn.com/course/%EC%8A%A4%ED%94%84%EB%A7%81-db-1/dashboard





# 자바 예외의 이해

## 자바 예외 계층

<img width="805" alt="DB1" src="https://github.com/whxogus215/Backend-Study-Archive/assets/70999462/bf6b1fc2-1902-42d4-8f8c-8f32e05a6e6a">

<img width="806" alt="DB 2" src="https://github.com/whxogus215/Backend-Study-Archive/assets/70999462/af083146-d28e-40be-895f-b45f6a120468">

- 체크 예외 : 컴파일러가 **체크하는 예외이다.** 따라서 체크 예외를 처리하지 않으면 컴파일 에러가 발생한다.
    - 여기서 처리란 `try-catch` 혹은 `throws`를 뜻한다.
- 언체크 예외 : 컴파일러가 **체크하지 않는 예외이다.** 따라서 예외를 처리하지 않아도 컴파일이 된다.

<img width="815" alt="DB3" src="https://github.com/whxogus215/Backend-Study-Archive/assets/70999462/600bf600-9b5e-4ae4-97fd-69be4b673e6e">

예외는 처리하거나 던지거나 둘 중 하나를 반드시 해야 한다. 예외를 잡거나 던질 경우, 해당 예외의 자식 예외들도 다같이 처리된다.
- `Exception`을 `catch`로 잡을 경우, `Exception`을 포함한 하위 예외들도 잡을 수 있게 된다.
- `Exception`을 `throws`로 던질 경우, `Exception`을 포함한 하위 예외들도 던질 수 있게 된다.

### 함부로 Exception으로 처리하거나 던지면 안되는 이유
따라서 `Exception`으로 한번에 던지거나 잡을 수가 있기 때문에 이를 사용하면 간편할 수는 있다. 하지만 이는 지저분하고 좋지 않은 코드이다.
왜냐하면 **최상위 예외로 처리할 경우, 처리되지 않아야 할 예외들도 싸잡아서 다 처리되기 때문이다.** throws도 마찬가지이다. `throws Exception`으로 해버리면
이 또한 하위 예외들도 전부 던지게 되는 것이므로 좋지 않은 코드이다. 

**예외를 처리하지 못하고 계속 던질 경우, 최종적으로 `main()`의 쓰레드에서 예외 로그를 출력하며 시스템이 종료된다.**
그러나 웹 어플리케이션의 경우, 여러 사용자의 요청을 처리하기 때문에 하나의 예외로 인해 시스템이 종료되어선 안된다.
따라서 던져진 예외를 **WAS가 잡아 처리하고, 사용자로 하여금 개발자가 만든 에러 페이지를 보여주도록 한다.**

## 체크 예외와 언체크 예외
### 체크 예외
```java
/**
     * Exception을 상속받은 예외는 체크 예외가 된다.
     */
    static class MyCheckedException extends Exception {
        public MyCheckedException(String message) {
            super(message); // 이미 구현된 생성자를 호출
        }
    }
```
이처럼 `Exception`을 상속받는 예외 클래스는 **체크 예외가 된다.** 이처럼 생성자로 에러 메세지를 받을 수도 있다.

```java
/**
     * Checked 예외는
     * 예외를 잡아서 처리하거나, 던지거나 둘 중 하나를 필수로 선택해야 한다.
     */
    static class Service {

        Repository repository = new Repository();

        /**
         * 예외를 잡아서 처리하는 코드
         */
        public void callCatch() {
            try {
                repository.call();
            } catch (MyCheckedException e) {
                // 예외 처리 로직
                log.info("예외 처리, message={}", e.getMessage(), e); // log.info 마지막에 예외 참조변수를 넣으면 stackTrace를 출력해준다.
            }
        }

        /**
         * 체크 예외를 밖으로 던지는 코드
         * 체크 예외는 예외를 잡지 않고 밖으로 던지려면 throws 예외를 메서드에 필수로 선언해야 한다.
         * @throws MyCheckedException
         */
        public void callThrow() throws MyCheckedException {
            repository.call();
        }
    }

    static class Repository {
        public void call() throws MyCheckedException {
            throw new MyCheckedException("ex");
        }
    }
}
```
- `log.info()`에서 마지막에 참조변수 e를 넣어주면 stackTrace를 출력해준다.
- 이처럼 체크 예외의 경우, 잡거나 던지거나하는 예외 처리를 반드시 해줘야 한다.
  - 예외 처리를 하지 않을 경우, `Unhandled exception`가 발생한다.

### 체크 예외의 장단점
- 장점 : 컴파일러가 예외를 체크하기 때문에 개발자가 실수할 일이 적어진다.
- 단점 : 개발자가 신경쓰고 싶지 않은 예외들까지 전부 처리를 해야 한다. 또한 의존관계 문제가 생긴다.(뒤에서 설명)

### 언체크 예외
```java
/**
     * RuntimeException을 상속받은 예외는 언체크 예외가 된다.
     */
    static class MyUncheckedException extends RuntimeException {
        public MyUncheckedException(String message) {
            super(message);
        }
    }
```
이처럼 `RuntimeException` 예외를 상속받는 예외 클래스는 전부 **언체크 예외가 된다.** 마찬가지로 생성자를 통해 에러 메시지를 받을 수 있다.

```java
/**
     * Unchecked 예외는
     * 예외를 잡거나, 던지지 않아도 된다.
     * 예외를 잡지 않으면 자동으로 밖으로 던진다.
     */
    static class Service {
        Repository repositoy = new Repository();

        /**
         * 필요한 경우 예외를 잡아서 처리하면 된다.
         */
        public void callCatch() {
            try {
                repositoy.call();
            } catch (MyUncheckedException e) {
                // 예외 처리 로직
                log.info("예외 처리, message={}", e.getMessage(), e);
            }
        }

        /**
         * 예외를 잡지 않아도 된다. 자연스럽게 상위로 넘어간다.
         * 체크 예외와 다르게 throws 예외 선언을 하지 않아도 된다.
         */
        public void callThrow() {
            repositoy.call();
        }
    }


    static class Repository {
        public void call() { // 언체크 에외이기 때문에 throws 선언 생략 가능(해도 상관은 없다.)
            throw new MyUncheckedException("ex");
        }
    }
```
언체크 예외는 `throws`를 통해 예외를 던지지 않아도 에러가 발생하지 않는다. 정확히는 **생략이 가능한 것이다.** `throws`를 생략해도
자동으로 던지게 된다. 

```java
@Test
void unchecked_throw() {
    Service service = new Service();
    Assertions.assertThatThrownBy(() -> service.callThrow())
            .isInstanceOf(MyUncheckedException.class);
}
```
다만 예외를 최종적으로 처리할 경우에는 이처럼 `assertThatThrownBy()`를 통해 예외 클래스를 확인해야 한다.

### 언체크 예외의 장단점
- 장점 : 신경쓰고 싶지 않은 언체크 예외를 무시할 수 있다. 언체크는 `throws`를 생략할 수 있기 때문이다. 이는 의존관계로 참조하지 않아도 되는 장점이 된다.
- 단점 : 개발자의 실수로 인해 예외가 누락될 수 있다. 언제 어느 부분에서 예외가 발생했는지 체크하기가 어렵기 때문이다. 반면에 체크 예외는 컴파일 단계에서
바로바로 확인이 가능하다.


# 체크 예외 활용
기본적으로는 **언체크 예외를 써야 한다.** 체크 예외를 사용해야 할 경우는 비즈니스 로직 상 의도적으로 던지는 예외,
즉 반드시 처리되어야 하는 예외일 경우 체크 예외를 활용한다. 그 외에는 다 언체크 예외를 사용하는 것을 원칙으로 한다.

예를 들어, 계좌 이체 실패 예외나 로그인 관련 예외 등은 개발자가 빼먹지 않고 반드시 처리해야 되는 중요 예외사항이다.
물론, 이러한 경우에도 언체크 예외를 활용할 수 있으나 개발자가 까먹고 넘어가지 않게 하려면 체크 예외를 쓰는게 좋다.

## 체크 예외의 문제점
웹 애플리케이션 개발에서 언체크 예외를 주로 사용해야하는 이유는 뭘까? 바로 상관없는 계층에서 해당 예외에 대한
의존관계가 생기기 때문이다.

[그림1]

체크 예외를 사용할 경우, 해당 그림에서처럼 서비스 계층은 시스템 계층에서 올라온 예외를 처리해야 한다.
이 때, 서비스 계층에서는 해당 에러를 처리할 수 없다. 따라서 서비스도 윗 계층으로 예외를 던진다.
결국 이처럼 해결되기 어려운 오류들은 별도의 로그를 통해 개발자가 직접 확인해야 하고, API의 경우
500번대 상태 코드를 반환해서 에러에 관련된 응답을 해야 한다.

어쨌든 에러와 관련 없는 계층들이 영향을 받는 것이 문제가 된다.

```java
@Slf4j
public class CheckedAppTest {
 @Test
 void checked() {
   Controller controller = new Controller();
   assertThatThrownBy(() -> controller.request())
            .isInstanceOf(Exception.class);
 }
 static class Controller {
    Service service = new Service();
    public void request() throws SQLException, ConnectException {
        service.logic();
    }
 }
 static class Service {
    Repository repository = new Repository();
    NetworkClient networkClient = new NetworkClient();
    public void logic() throws SQLException, ConnectException {
        repository.call();
        networkClient.call();
    }
 }
 static class NetworkClient {
    public void call() throws ConnectException {
        throw new ConnectException("연결 실패");
    }
 }
 static class Repository {
    public void call() throws SQLException {
        throw new SQLException("ex");
    }
 }
}
```
이처럼 던진 에러로 인해 모든 메서드에서 다 `throws 예외`를 해야 한다. 만약, 여기서 예외가 추가될 경우,
**또 다른 메서드들을 하나하나 `throws 예외`를 추가해야 하는 것이다.**

1. 복구 불가능한 예외
- 대부분의 예외는 복구가 불가능한 예외라는 것을 인지해야 한다. `SQLException`의 경우, DB의 쿼리문이 잘못됐거나
DB 서버 내부가 잘못됐을 가능성도 있다. 이러한 것들은 서비스나 컨트롤러에서 해결할 수 없다. 그럼에도 불구하고
**체크 예외의 경우, 해당 계층들도 예외를 처리해야 할 의무를 갖게 되는 것이다.**

이러한 시스템의 경우, 일관적으로 처리해야 하며 **오류 로그를 남기고, 서블릿 필터, 인터셉터, 스프링의
`ControllerAdvice`를 사용해서 공통으로 처리해야 한다.**

2. 의존 관계에 대한 문제
- 앞서 말했듯이 복구 불가능한 예외를 다른 계층들에서 `throws`를 통해 의존하고 있다. `throws`를 사용했다는 것은
어쨌든 해당 계층에서 해당 예외에 대해 알고 있다는 뜻인거다. JDBC에 관한 예외를 의존하다가
JPA로 바뀐다면 다시 해당 예외로 일일이 바꿔줘야 한다. 이는 OCP, DI를 통한 스프링의 객체지향 구조를
의미없게 만들어버린다.

3. Exception으로 던지기
- 앞서 말했듯이, 복잡한 예외들을 `throws Exception`으로 처리하는 것은 좋지 않은 방법이다.
이러면 **처리해야 할(catch) 예외들까지 전부 던져버리기 때문에 처리하지 않았음에도 컴파일러 에러가 발생하지 않는다.**
즉, 꼭 필요한 경우가 아니라면 가급적 `Exception`으로 던져버리는 것은 좋지 않다!!!

# 언체크 예외 활용
언체크 예외, 즉 **런타임 예외를 활용하도록 한다.** 

[그림 3]

이처럼 런타임 예외이기 때문에 **컨트롤러와 서비스에서 해당 예외를 처리하지 않아도 된다.** 체크 예외때와 달리
해당 예외에 대한 의존관계를 갖지 않는다.

```java
@Slf4j
public class UncheckedAppTest {
    @Test
    void unchecked() {
        Controller controller = new Controller();
        assertThatThrownBy(() -> controller.request())
                .isInstanceOf(Exception.class);
    }
    @Test
    void printEx() {
        Controller controller = new Controller();
        try {
            controller.request();
        } catch (Exception e) {
            //e.printStackTrace();
            log.info("ex", e);
        }
    }
    static class Controller {
        Service service = new Service();
        public void request() {
            service.logic();
        }
    }
    static class Service {
        Repository repository = new Repository();
        NetworkClient networkClient = new NetworkClient();
        public void logic() {
            repository.call();
            networkClient.call();
        }
    }
    static class NetworkClient {
        public void call() {
            throw new RuntimeConnectException("연결 실패");
        }
    }
    static class Repository {
        public void call() {
            try {
                runSQL();
            } catch (SQLException e) {
                throw new RuntimeSQLException(e);
            }
        }
        private void runSQL() throws SQLException {
            throw new SQLException("ex");
        }
    }
    static class RuntimeConnectException extends RuntimeException {
        public RuntimeConnectException(String message) {
            super(message);
        }
    }
    static class RuntimeSQLException extends RuntimeException {
        public RuntimeSQLException() {
        }
        public RuntimeSQLException(Throwable cause) {
            super(cause);
        }
    }
}
```
- 이처럼 예외가 발생되는 곳 이외에는 `throws`를 선언하지 않는다.

이처럼 복구가 불가능한 런타임 에러를 다른 계층에서 신경쓰지 않아도 된다는 장점이 있다.
또한 체크 예외와 달리 강제로 의존하지 않아도 된다.

[그림 4]

**이처럼 기술이 변경되어도 예외가 공통적으로 처리되는 부분을 제외하고는 아무 변경이 일어나지 않는다.**

## 런타임 예외의 문서화
런타임 예외는 컴파일러가 체크하지 않기 때문에 개발자가 처리하지 못할 가능성이 있다.
따라서 런타임 예외가 발생하는 경우에는 문서화가 중요하다.

[그림 5]

이처럼 런타임 예외를 던지는 메서드에 어떠한 예외가 던져지는지 명시해주면 개발자가 확인할 수 있다.

## 예외 전환과 스택 트레이스
런타임 예외를 주로 활용하기로 했기 때문에 체크 예외의 경우 언체크 예외(런타이 예외)로 바꿔주는 경우가 많다.

```java
public void call() {
    try {
        runSQL();
    } catch (SQLException e) {
        throw new RuntimeSQLException(e);
    }
}
```
- 이처럼 체크 예외인 `SQLException`을 잡아서 언체크 예외를 생성할 수 있다. 이 때, 언체크 예외의 생성자에
기존 예외를 넣을 수 있다. 이렇게 하면 예외 스택 트레이스를 출력할 때, 언체크 예외와 함께 체크 예외도 같이 출력된다.

```java
13:10:45.626 [Test worker] INFO hello.jdbc.exception.basic.UncheckedAppTest - 
ex
hello.jdbc.exception.basic.UncheckedAppTest$RuntimeSQLException: 
java.sql.SQLException: ex
at 
hello.jdbc.exception.basic.UncheckedAppTest$Repository.call(UncheckedAppTest.ja
va:61)
at 
hello.jdbc.exception.basic.UncheckedAppTest$Service.logic(UncheckedAppTest.java
:45)
at 
hello.jdbc.exception.basic.UncheckedAppTest$Controller.request(UncheckedAppTest
.java:35)
at 
hello.jdbc.exception.basic.UncheckedAppTest.printEx(UncheckedAppTest.java:24)
        
Caused by: java.sql.SQLException: ex
at 
hello.jdbc.exception.basic.UncheckedAppTest$Repository.runSQL(UncheckedAppTest.
java:66)
at 
hello.jdbc.exception.basic.UncheckedAppTest$Repository.call(UncheckedAppTest.ja
va:59)
```
`Casued by` 항목을 통해 어느 예외로부터 발생된 것인지 확인할 수 있다.

만약, DB와 관련된 체크 예외가 발생했고, 이를 잡아 런타임 에러를 던질 경우 런타임 에러와
체크 예외가 같이 나와야 한다. 기존 예외를 포함시키지 않으면 런타임 에러만 로그에 출력된다.


**따라서 예외를 전환할 때는 꼭 기존 예외를 포함시켜야 한다.**

